### ISSUE TITLE
Add a README to the project

### ISSUE THREAD

**Issue by anoadragon453** [joakimvonanka/Matrix-Remind-me-bot#2]
When you look at other projects such as [Dendrite](https://github.com/matrix-org/dendrite), you'll notice that they have a large text document under the files that contains information about what the software is and does, and instructions on how to run it. This information is kept in a file called `README.md`, and you can view Dendrite's here: https://github.com/matrix-org/dendrite/blob/master/README.md, and the source code of it here: https://raw.githubusercontent.com/matrix-org/dendrite/master/README.md

Adding such a file can help people get started with your project, and typically contains the following elements:

* Project name
* What the project is
* How to setup and run the project yourself

The `README.md` file ends in `.md` because it's a markdown file. Simply create this file, write it in markdown (here's a very quick [guide](https://guides.github.com/features/mastering-markdown/)!) and put it in your project's root directory (next to `package.json` etc.) and your project's code will be suddenly much more approachable :)

**Comment by joakimvonanka** [comment]
Readme now added.
